"""Initial migration with all models

Revision ID: 090937605b79
Revises: 
Create Date: 2025-09-25 15:50:08.608096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090937605b79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rector_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('identidad', sa.String(length=40), nullable=True),
    sa.Column('firma_url', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('genero', sa.Enum('femenino', 'masculino', 'otro', 'sin_especificar', name='user_genders'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'docente', name='user_roles'), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo', name='user_status'), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('security_stamp', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento'),
    sa.UniqueConstraint('documento', 'email', name='uq_documento_email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('asignaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('configuracion_libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel_aprobacion', sa.Float(), nullable=False),
    sa.Column('nota_superior', sa.Float(), nullable=False),
    sa.Column('nota_alto', sa.Float(), nullable=False),
    sa.Column('nota_basico', sa.Float(), nullable=False),
    sa.Column('año_lectivo_actual', sa.Integer(), nullable=False),
    sa.Column('formato_exportacion', sa.String(length=20), nullable=False),
    sa.Column('incluir_firma', sa.Boolean(), nullable=False),
    sa.Column('incluir_sello', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=5), nullable=False),
    sa.Column('fecha_fin', sa.String(length=5), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('anio_periodo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio_lectivo', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=5), nullable=False),
    sa.Column('fecha_fin', sa.String(length=5), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=False),
    sa.Column('id_asignatura', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_periodo', sa.Integer(), nullable=True),
    sa.Column('anio_lectivo', sa.Integer(), nullable=False),
    sa.Column('horas_impartidas', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_asignatura'], ['asignaturas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_docente'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=True),
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=False),
    sa.Column('campos_incluidos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matricula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.Enum('femenino', 'masculino', name='genero_types'), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('año_lectivo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('fecha_matricula', sa.Date(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_transferencia', sa.DateTime(), nullable=True),
    sa.Column('transferido_por', sa.String(length=100), nullable=True),
    sa.Column('observaciones_transferencia', sa.Text(), nullable=True),
    sa.Column('curso_origen', sa.String(length=100), nullable=True),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento', 'año_lectivo', name='uq_documento_anio')
    )
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('id_asignacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_asignacion'], ['asignaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_asignacion', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_asignacion'], ['asignaciones.id'], ),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boletines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('grades_data', sa.Text(), nullable=True),
    sa.Column('anio_lectivo', sa.String(length=9), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('generated_date', sa.DateTime(), nullable=True),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=True),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id'], ),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_asignacion', sa.Integer(), nullable=False),
    sa.Column('id_periodo', sa.Integer(), nullable=False),
    sa.Column('fecha_calificacion', sa.Date(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_asignacion'], ['asignaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_periodo'], ['periodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inclusiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('tipo_necesidad', sa.String(length=100), nullable=False),
    sa.Column('plan_apollo', sa.Text(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('detalles', sa.String(length=300), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('académica', 'asistencia', 'disciplinaria'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('detalles', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('id_matricula', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.Enum('Matricula', 'Mensualidad', 'Derecho a grado', name='concepto_enum'), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('efectivo', 'transferencia', 'tarjeta', 'consignacion', name='metodo_pago_enum'), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'pagado', name='estado_pago_enum'), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('eliminado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_matricula'], ['matricula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('observacion')
    op.drop_table('inclusiones')
    op.drop_table('calificacion')
    op.drop_table('boletines')
    op.drop_table('asistencias')
    op.drop_table('actividades')
    op.drop_table('matricula')
    op.drop_table('informes')
    op.drop_table('asignaciones')
    op.drop_table('anio_periodo')
    op.drop_table('periodos')
    op.drop_table('cursos')
    op.drop_table('configuracion_libro')
    op.drop_table('asignaturas')
    op.drop_table('usuarios')
    op.drop_table('system_config')
    op.drop_table('rector_config')
    # ### end Alembic commands ###
